// Curated Windows Event ID reference. Verified against Microsoft Learn
// auditing docs, the Sysmon schema, and the PowerShell/Defender operational
// channels. Fields:
//   id, log (channel), cat (category key), crit (high|medium|low|info),
//   title, desc, sec (security relevance, optional),
//   sub {label, cols, rows} (optional sub-code table),
//   query (a Get-WinEvent one-liner)
window.TWB_WIN_EVENTS = (function () {
  "use strict";

  var LOGON_TYPES = {
    label: "Logon Type",
    cols: ["type", "name", "meaning"],
    rows: [
      ["2", "Interactive", "At the keyboard/console of this computer."],
      ["3", "Network", "From the network — SMB, RPC, mapped drives, remote WMI."],
      ["4", "Batch", "Scheduled task or batch process running as a user."],
      ["5", "Service", "A service started by the Service Control Manager."],
      ["7", "Unlock", "The workstation was unlocked."],
      ["8", "NetworkCleartext", "Network logon with the password sent in cleartext (e.g. IIS basic auth)."],
      ["9", "NewCredentials", "runas /netonly — same local identity, different outbound credentials."],
      ["10", "RemoteInteractive", "RDP / Terminal Services / Remote Assistance."],
      ["11", "CachedInteractive", "Logged on with locally cached domain credentials; the DC was not reached."]
    ]
  };

  function q(log, id) {
    return "Get-WinEvent -FilterHashtable @{LogName='" + log + "';Id=" + id + "}";
  }

  var E = [
    // ---- Logon / Logoff (Security) ----
    { id: 4624, log: "Security", cat: "logon", crit: "info",
      title: "An account was successfully logged on",
      desc: "A logon session was created. The Logon Type reveals how (console, network, RDP, service, etc.) and the Logon ID ties it to the matching 4634/4647 logoff.",
      sec: "Baseline for who-logged-on-where. Type 10 (RDP) and type 3 (network) from unexpected hosts, or type 9 (runas /netonly), are common lateral-movement signals.",
      sub: LOGON_TYPES },
    { id: 4625, log: "Security", cat: "logon", crit: "medium",
      title: "An account failed to log on",
      desc: "A logon attempt failed. The Status/Sub Status code says why; the Logon Type says how it was attempted.",
      sec: "Bursts of 4625 are password spraying or brute force. 0xC0000064 (no such user) in volume is user enumeration; repeated 0xC000006A is password guessing against a known account.",
      sub: {
        label: "Status / Sub Status codes",
        cols: ["code", "meaning"],
        rows: [
          ["0xC0000064", "User name does not exist (often enumeration)."],
          ["0xC000006A", "Correct user name, wrong password."],
          ["0xC000006D", "Bad user name or authentication info (generic)."],
          ["0xC000006F", "Logon outside of authorized hours."],
          ["0xC0000070", "Logon from an unauthorized workstation."],
          ["0xC0000071", "Password has expired."],
          ["0xC0000072", "Account is disabled by an administrator."],
          ["0xC0000193", "Account has expired."],
          ["0xC0000224", "User must change password at next logon."],
          ["0xC0000234", "Account is currently locked out."],
          ["0xC000015B", "User has not been granted the requested logon type here."],
          ["0xC000005E", "No logon servers available (infrastructure, not attack)."]
        ]
      } },
    { id: 4634, log: "Security", cat: "logon", crit: "info",
      title: "An account was logged off",
      desc: "A logon session ended. Correlate the Logon ID with the 4624 that opened it. Not always emitted (network sessions can end without it).",
      sec: "Pairs with 4624 to measure session duration." },
    { id: 4647, log: "Security", cat: "logon", crit: "info",
      title: "User initiated logoff",
      desc: "The user chose to log off (Start > Sign out), as opposed to a session teardown. More reliable than 4634 for interactive sessions.",
      sec: "Distinguishes a deliberate sign-out from a dropped session." },
    { id: 4648, log: "Security", cat: "logon", crit: "medium",
      title: "A logon was attempted using explicit credentials",
      desc: "A process authenticated as a different account than the caller — runas, mapped drive with alternate creds, or scheduled task with stored creds.",
      sec: "Classic lateral movement / credential-reuse indicator. Watch when the Subject and Target accounts differ and the target host is remote." },
    { id: 4672, log: "Security", cat: "logon", crit: "medium",
      title: "Special privileges assigned to new logon",
      desc: "The logon session was granted sensitive privileges (SeDebugPrivilege, SeTcbPrivilege, SeBackupPrivilege, etc.) — i.e. an administrative-equivalent logon.",
      sec: "Fires alongside 4624 for admin logons. A 4672 for an account that should never be privileged is worth an alert." },
    { id: 4778, log: "Security", cat: "logon", crit: "low",
      title: "A session was reconnected to a Window Station",
      desc: "An RDP or fast-user-switching session was reconnected. Includes the client name and address.",
      sec: "Reconnection to an existing RDP session — useful for tracking interactive access." },
    { id: 4779, log: "Security", cat: "logon", crit: "low",
      title: "A session was disconnected from a Window Station",
      desc: "An RDP/console session was disconnected (not logged off). The session keeps running.",
      sec: "Disconnected sessions persist — a way attackers keep an interactive foothold." },
    { id: 4800, log: "Security", cat: "logon", crit: "info",
      title: "The workstation was locked",
      desc: "The interactive session was locked (Win+L or timeout)." },
    { id: 4801, log: "Security", cat: "logon", crit: "info",
      title: "The workstation was unlocked",
      desc: "The interactive session was unlocked." },
    { id: 4776, log: "Security", cat: "logon", crit: "medium",
      title: "The domain controller attempted to validate credentials (NTLM)",
      desc: "NTLM credential validation on a DC or local SAM. Error code 0xC0000064/0xC000006A mirror the 4625 sub-status meanings.",
      sec: "NTLM auth on modern networks is worth scrutiny; volume of failures here is spray/brute-force against NTLM." },
    { id: 4768, log: "Security", cat: "kerberos", crit: "info",
      title: "A Kerberos authentication ticket (TGT) was requested",
      desc: "A user requested a TGT (AS-REQ) — i.e. Kerberos logon to the domain. The Result Code tells you if it succeeded or why it failed.",
      sec: "AS-REQ with encryption type 0x17 (RC4) can indicate AS-REP roasting or downgrade; watch accounts with pre-auth disabled.",
      sub: {
        label: "Common failure result codes",
        cols: ["code", "meaning"],
        rows: [
          ["0x6", "Client (user) not found in Kerberos database."],
          ["0x12", "Account disabled, expired, locked out, or restricted."],
          ["0x18", "Pre-authentication failed (wrong password)."],
          ["0x25", "Clock skew too great between client and DC."]
        ]
      } },
    { id: 4769, log: "Security", cat: "kerberos", crit: "medium",
      title: "A Kerberos service ticket (TGS) was requested",
      desc: "A user requested a service ticket for a specific SPN (TGS-REQ).",
      sec: "Kerberoasting: many 4769 for service SPNs with ticket encryption type 0x17 (RC4) from one user in a short window. Baseline SPN request patterns." },
    { id: 4771, log: "Security", cat: "kerberos", crit: "medium",
      title: "Kerberos pre-authentication failed",
      desc: "A TGT request failed pre-auth — usually a wrong password (failure code 0x18) or a disabled account (0x12).",
      sec: "The Kerberos equivalent of 4625; volume signals password guessing against the domain." },
    { id: 4770, log: "Security", cat: "kerberos", crit: "info",
      title: "A Kerberos service ticket was renewed",
      desc: "An existing TGS was renewed within its lifetime." },

    // ---- Account management (Security) ----
    { id: 4720, log: "Security", cat: "account", crit: "high",
      title: "A user account was created",
      desc: "A new user account was created in AD or the local SAM. Subject = who created it, Target = the new account.",
      sec: "Unexpected account creation — especially on a DC or by a non-admin process — is a persistence hallmark." },
    { id: 4722, log: "Security", cat: "account", crit: "medium",
      title: "A user account was enabled",
      desc: "A previously disabled account was enabled.",
      sec: "Re-enabling a dormant or service account can be a stealthy persistence move." },
    { id: 4723, log: "Security", cat: "account", crit: "low",
      title: "An attempt was made to change an account's password",
      desc: "A user changed their own password (knowing the old one)." },
    { id: 4724, log: "Security", cat: "account", crit: "medium",
      title: "An attempt was made to reset an account's password",
      desc: "An administrator reset another account's password (without the old one).",
      sec: "Reset of a privileged or service account by an unexpected admin is worth investigating." },
    { id: 4725, log: "Security", cat: "account", crit: "low",
      title: "A user account was disabled",
      desc: "An account was disabled." },
    { id: 4726, log: "Security", cat: "account", crit: "medium",
      title: "A user account was deleted",
      desc: "An account was deleted.",
      sec: "Deletion of accounts — particularly right after suspicious activity — can be cleanup / anti-forensics." },
    { id: 4738, log: "Security", cat: "account", crit: "low",
      title: "A user account was changed",
      desc: "An attribute of a user account changed (UAC flags, home dir, etc.). The event lists which fields.",
      sec: "Watch for 'Don't Expire Password' or 'Password Not Required' flags being set on accounts." },
    { id: 4740, log: "Security", cat: "account", crit: "medium",
      title: "A user account was locked out",
      desc: "An account exceeded the bad-password threshold and was locked. The Caller Computer Name shows where the bad attempts came from.",
      sec: "Repeated lockouts point at a brute-force source or a stale cached credential hammering the DC." },
    { id: 4767, log: "Security", cat: "account", crit: "low",
      title: "A user account was unlocked",
      desc: "An administrator unlocked a locked-out account." },
    { id: 4728, log: "Security", cat: "account", crit: "high",
      title: "A member was added to a security-enabled global group",
      desc: "A user was added to a global group — this is the event for adding to Domain Admins and similar.",
      sec: "Addition to Domain Admins / Enterprise Admins / Schema Admins is a top privilege-escalation alert." },
    { id: 4732, log: "Security", cat: "account", crit: "high",
      title: "A member was added to a security-enabled local group",
      desc: "A user was added to a local group — this is the event for adding to the local Administrators group.",
      sec: "Addition to local Administrators or Remote Desktop Users on a workstation/server is a common persistence step." },
    { id: 4756, log: "Security", cat: "account", crit: "high",
      title: "A member was added to a security-enabled universal group",
      desc: "A user was added to a universal group (forest-wide scope).",
      sec: "Universal groups can grant forest-wide access; unexpected additions warrant review." },
    { id: 4729, log: "Security", cat: "account", crit: "medium",
      title: "A member was removed from a security-enabled global group",
      desc: "A user was removed from a global group.",
      sec: "Removal from a group can be part of covering tracks or disrupting defenders' access." },
    { id: 4733, log: "Security", cat: "account", crit: "medium",
      title: "A member was removed from a security-enabled local group",
      desc: "A user was removed from a local group (e.g. local Administrators)." },
    { id: 4735, log: "Security", cat: "account", crit: "low",
      title: "A security-enabled local group was changed",
      desc: "A local group's properties changed." },
    { id: 4737, log: "Security", cat: "account", crit: "low",
      title: "A security-enabled global group was changed",
      desc: "A global group's properties changed." },
    { id: 4781, log: "Security", cat: "account", crit: "medium",
      title: "The name of an account was changed",
      desc: "An account was renamed.",
      sec: "Renaming a built-in account (e.g. disguising a new admin) can hide it from casual review." },

    // ---- Process / object (Security) ----
    { id: 4688, log: "Security", cat: "process", crit: "medium",
      title: "A new process has been created",
      desc: "A process started. Includes the new process name, PID, the parent process, and (with command-line auditing enabled) the full command line and the creator account.",
      sec: "The single most valuable hunting event. Enable command-line logging. Watch for LOLBins (powershell, wmic, mshta, rundll32, regsvr32), odd parent-child chains (winword.exe -> cmd.exe), and execution from temp paths." },
    { id: 4689, log: "Security", cat: "process", crit: "info",
      title: "A process has exited",
      desc: "A process ended, with its exit status. Pairs with 4688 by PID." },
    { id: 4657, log: "Security", cat: "object", crit: "medium",
      title: "A registry value was modified",
      desc: "An audited registry value was created, modified, or deleted. Requires a SACL on the key.",
      sec: "Audit Run keys, services, and known persistence locations to catch autostart tampering." },
    { id: 4663, log: "Security", cat: "object", crit: "low",
      title: "An attempt was made to access an object",
      desc: "An audited file/registry/object access actually occurred (the access mask shows read/write/delete). Requires SACLs.",
      sec: "Scoped file-access auditing on sensitive shares surfaces data staging/theft." },
    { id: 4656, log: "Security", cat: "object", crit: "low",
      title: "A handle to an object was requested",
      desc: "A handle to an audited object was requested (may be denied). Precedes 4663.",
      sec: "Failed handle requests (access denied) on protected objects can reveal probing." },
    { id: 4660, log: "Security", cat: "object", crit: "low",
      title: "An object was deleted",
      desc: "An audited object was deleted. Correlate with the 4656 that opened the handle." },
    { id: 4674, log: "Security", cat: "object", crit: "low",
      title: "An operation was attempted on a privileged object",
      desc: "A privileged system operation was performed against an object using a sensitive privilege." },
    { id: 5140, log: "Security", cat: "share", crit: "low",
      title: "A network share object was accessed",
      desc: "A network share was accessed over SMB. Includes the share name and source address.",
      sec: "Access to ADMIN$ or C$ from an unexpected host is a lateral-movement / PsExec-style signal." },
    { id: 5145, log: "Security", cat: "share", crit: "low",
      title: "A network share object was checked for access (detailed)",
      desc: "Detailed file-share access check, including the relative target filename. Very high volume — enable selectively.",
      sec: "Access to PSEXECSVC, or reads of SYSVOL scripts/GPP files, stand out here." },
    { id: 5142, log: "Security", cat: "share", crit: "low",
      title: "A network share object was added",
      desc: "A new SMB share was created.",
      sec: "New shares created by an attacker can stage tools or exfiltrate data." },

    // ---- Policy / audit (Security) ----
    { id: 1102, log: "Security", cat: "policy", crit: "high",
      title: "The audit log was cleared",
      desc: "The Security event log was cleared. Records who did it — this event survives the clear because it's written after.",
      sec: "A textbook anti-forensics action. Almost always worth an immediate alert unless part of a known maintenance window." },
    { id: 4719, log: "Security", cat: "policy", crit: "high",
      title: "System audit policy was changed",
      desc: "The audit policy itself was modified — subcategories enabled or disabled.",
      sec: "Attackers disable auditing to go dark. Alert on any unexpected 4719, especially disabling process or logon auditing." },
    { id: 4907, log: "Security", cat: "policy", crit: "low",
      title: "Auditing settings on an object were changed",
      desc: "The SACL (audit settings) on a file or registry object changed." },
    { id: 4904, log: "Security", cat: "policy", crit: "low",
      title: "An attempt was made to register a security event source",
      desc: "A new event log source was registered." },
    { id: 4616, log: "Security", cat: "policy", crit: "medium",
      title: "The system time was changed",
      desc: "The system clock was changed, with the old and new time and who did it.",
      sec: "Time manipulation can break Kerberos and, more importantly, is used to confuse log timelines. Ignore the normal w32time service adjustments." },

    // ---- Scheduled tasks (Security) ----
    { id: 4698, log: "Security", cat: "task", crit: "high",
      title: "A scheduled task was created",
      desc: "A new scheduled task was registered. The event embeds the task's full XML definition — action, trigger, and run-as account.",
      sec: "Scheduled tasks are a top persistence mechanism. Inspect the embedded XML for suspicious actions (powershell, script paths in temp)." },
    { id: 4699, log: "Security", cat: "task", crit: "medium",
      title: "A scheduled task was deleted",
      desc: "A scheduled task was removed.",
      sec: "Deletion after use is cleanup; also watch for defenders' tasks being removed." },
    { id: 4700, log: "Security", cat: "task", crit: "low",
      title: "A scheduled task was enabled",
      desc: "A disabled task was enabled." },
    { id: 4701, log: "Security", cat: "task", crit: "low",
      title: "A scheduled task was disabled",
      desc: "A task was disabled — potentially a defensive/monitoring task." },
    { id: 4702, log: "Security", cat: "task", crit: "medium",
      title: "A scheduled task was updated",
      desc: "An existing task's definition changed. The new XML is embedded.",
      sec: "Modifying a legitimate task to add a malicious action hides persistence in a trusted name." },

    // ---- TaskScheduler operational (richer task telemetry) ----
    { id: 106, log: "Microsoft-Windows-TaskScheduler/Operational", cat: "task", crit: "low",
      title: "A user registered a scheduled task",
      desc: "Operational-log counterpart to 4698 — task registered, with the task name and user." },
    { id: 140, log: "Microsoft-Windows-TaskScheduler/Operational", cat: "task", crit: "low",
      title: "A scheduled task was updated",
      desc: "Operational-log record that a task definition was updated." },
    { id: 141, log: "Microsoft-Windows-TaskScheduler/Operational", cat: "task", crit: "low",
      title: "A scheduled task was deleted",
      desc: "Operational-log record that a task was deleted, with the user who did it." },
    { id: 200, log: "Microsoft-Windows-TaskScheduler/Operational", cat: "task", crit: "info",
      title: "A scheduled task action started",
      desc: "A task launched its action (executable/script). Shows the exact command run.",
      sec: "Ties a persistence task to the process it actually spawned." },

    // ---- Services (System) ----
    { id: 7045, log: "System", cat: "service", crit: "high",
      title: "A new service was installed",
      desc: "The Service Control Manager installed a new service, logging the service name, image path, service type, and start type.",
      sec: "PsExec, Cobalt Strike, and many RATs install a service to run as SYSTEM. Image paths in temp, or random service names, are strong signals." },
    { id: 7040, log: "System", cat: "service", crit: "low",
      title: "The start type of a service was changed",
      desc: "A service's start type changed (e.g. disabled -> auto).",
      sec: "Disabling a security service (Defender, event log, WinDefend) or auto-starting a new one is worth attention." },
    { id: 7036, log: "System", cat: "service", crit: "info",
      title: "A service entered the running/stopped state",
      desc: "A service changed run state. Very high volume; useful for confirming a specific service stopped.",
      sec: "Watch for the Windows Event Log or Defender service stopping unexpectedly." },
    { id: 7034, log: "System", cat: "service", crit: "low",
      title: "A service terminated unexpectedly",
      desc: "A service crashed. Includes how many times it has done so.",
      sec: "A security service crashing repeatedly can be tampering rather than a bug." },
    { id: 7035, log: "System", cat: "service", crit: "info",
      title: "A service was sent a start/stop control",
      desc: "The SCM sent a control signal to a service." },
    { id: 7009, log: "System", cat: "service", crit: "low",
      title: "A timeout was reached waiting for a service to connect",
      desc: "A service didn't respond to the SCM in time — often benign, sometimes a sign of a hung or hooked service." },
    { id: 7000, log: "System", cat: "service", crit: "low",
      title: "A service failed to start",
      desc: "A service failed to start due to an error." },

    // ---- System (System) ----
    { id: 1074, log: "System", cat: "system", crit: "low",
      title: "The system was shut down or restarted by a user/process",
      desc: "A shutdown/restart was initiated, with the process, user, and reason.",
      sec: "Unexpected reboots can accompany driver loads, updates pushed by an attacker, or evasion." },
    { id: 6005, log: "System", cat: "system", crit: "info",
      title: "The Event Log service was started",
      desc: "Logged at boot when the event log service starts — effectively a 'system booted' marker." },
    { id: 6006, log: "System", cat: "system", crit: "info",
      title: "The Event Log service was stopped",
      desc: "Logged at clean shutdown — a 'system going down cleanly' marker." },
    { id: 6008, log: "System", cat: "system", crit: "medium",
      title: "The previous system shutdown was unexpected",
      desc: "The last shutdown was dirty (crash, power loss, hard reset).",
      sec: "An unexpected shutdown around suspicious activity can indicate a crash from exploitation or deliberate power-off." },
    { id: 6013, log: "System", cat: "system", crit: "info",
      title: "System uptime report",
      desc: "Daily record of how long the system has been up." },
    { id: 41, log: "System", cat: "system", crit: "medium",
      title: "The system rebooted without cleanly shutting down (Kernel-Power)",
      desc: "Kernel-Power event marking a reboot without a clean shutdown first.",
      sec: "Corroborates 6008; clusters can indicate instability caused by exploitation or a bad driver." },

    // ---- PowerShell (operational + classic) ----
    { id: 4104, log: "Microsoft-Windows-PowerShell/Operational", cat: "powershell", crit: "high",
      title: "PowerShell script block logging",
      desc: "Records the actual script block content executed — even if it was obfuscated or fileless. Requires Script Block Logging (enabled via GPO).",
      sec: "The best window into fileless PowerShell attacks. Warning-level 4104 events flag scripts PowerShell itself judged suspicious (e.g. AMSI-triggering). Hunt for encoded commands, download cradles, and Invoke-* tradecraft." },
    { id: 4103, log: "Microsoft-Windows-PowerShell/Operational", cat: "powershell", crit: "medium",
      title: "PowerShell module/pipeline logging",
      desc: "Records pipeline execution details and parameter binding when Module Logging is enabled.",
      sec: "Complements 4104 with the commands and arguments actually invoked." },
    { id: 400, log: "Windows PowerShell", cat: "powershell", crit: "low",
      title: "Engine state changed to Available (PowerShell started)",
      desc: "Classic-log event marking a PowerShell engine starting. HostName reveals whether it's the console, ISE, or a non-interactive host.",
      sec: "A HostName that isn't a normal shell (e.g. an unusual custom host) can indicate PowerShell embedded in malware." },
    { id: 800, log: "Windows PowerShell", cat: "powershell", crit: "low",
      title: "Pipeline execution details",
      desc: "Classic-log record of pipeline execution; predates script block logging and captures less." },
    { id: 600, log: "Windows PowerShell", cat: "powershell", crit: "low",
      title: "Provider lifecycle (e.g. started)",
      desc: "Classic-log provider start/stop; the Registry/WSMan providers starting can accompany remoting." },

    // ---- Sysmon (operational) ----
    { id: 1, log: "Microsoft-Windows-Sysmon/Operational", cat: "sysmon", crit: "medium",
      title: "Sysmon: Process creation",
      desc: "Richest process-creation record available: full command line, hashes, parent process and its command line, and the signing status of the image.",
      sec: "The cornerstone Sysmon event. Superior to 4688 thanks to hashes and parent command line. Hunt LOLBins, suspicious parents, and unsigned images from temp." },
    { id: 3, log: "Microsoft-Windows-Sysmon/Operational", cat: "sysmon", crit: "medium",
      title: "Sysmon: Network connection",
      desc: "A process made a TCP/UDP connection, with the source/destination address, port, and the initiating process and user.",
      sec: "Beaconing, C2, and unexpected outbound from LOLBins (e.g. rundll32 connecting to the internet) surface here." },
    { id: 7, log: "Microsoft-Windows-Sysmon/Operational", cat: "sysmon", crit: "low",
      title: "Sysmon: Image loaded",
      desc: "A module (DLL) was loaded, with its hash and signature status. High volume — scope it.",
      sec: "Unsigned or suspiciously-named DLLs loaded into trusted processes reveal DLL sideloading." },
    { id: 8, log: "Microsoft-Windows-Sysmon/Operational", cat: "sysmon", crit: "high",
      title: "Sysmon: CreateRemoteThread",
      desc: "A process created a thread in another process — the core primitive of code injection.",
      sec: "A strong injection signal. Legitimate uses exist (some AV, debuggers), so baseline the source processes." },
    { id: 10, log: "Microsoft-Windows-Sysmon/Operational", cat: "sysmon", crit: "high",
      title: "Sysmon: Process access",
      desc: "A process opened a handle to another process, with the granted access mask and call stack.",
      sec: "Access to lsass.exe with PROCESS_VM_READ (0x0010) is the signature of credential dumping (Mimikatz-style)." },
    { id: 11, log: "Microsoft-Windows-Sysmon/Operational", cat: "sysmon", crit: "low",
      title: "Sysmon: File created",
      desc: "A file was created, with the creating process and target path.",
      sec: "Drops into Startup folders, temp, or ADS surface staging and persistence." },
    { id: 13, log: "Microsoft-Windows-Sysmon/Operational", cat: "sysmon", crit: "medium",
      title: "Sysmon: Registry value set",
      desc: "A registry value was set, with the process and the value data.",
      sec: "Autorun keys (Run, RunOnce), service ImagePaths, and Winlogon shell modifications are persistence gold here." },
    { id: 22, log: "Microsoft-Windows-Sysmon/Operational", cat: "sysmon", crit: "low",
      title: "Sysmon: DNS query",
      desc: "A process resolved a hostname, with the query and result and the initiating process.",
      sec: "DNS to newly-registered or algorithmically-generated domains, or from LOLBins, indicates C2." },
    { id: 15, log: "Microsoft-Windows-Sysmon/Operational", cat: "sysmon", crit: "low",
      title: "Sysmon: FileCreateStreamHash (alternate data stream)",
      desc: "A file was written to an NTFS alternate data stream — includes the Zone.Identifier mark-of-the-web and the content hash.",
      sec: "ADS is a classic hiding place; MOTW presence/absence tells you whether a file was downloaded." },
    { id: 23, log: "Microsoft-Windows-Sysmon/Operational", cat: "sysmon", crit: "low",
      title: "Sysmon: File delete (archived)",
      desc: "A file was deleted and archived by Sysmon for recovery.",
      sec: "Captures tools the attacker tried to delete after use." },
    { id: 25, log: "Microsoft-Windows-Sysmon/Operational", cat: "sysmon", crit: "high",
      title: "Sysmon: Process tampering",
      desc: "Detects process hollowing / herpaderping-style image tampering.",
      sec: "A high-fidelity signal for advanced injection and evasion techniques." },

    // ---- Windows Defender (operational) ----
    { id: 1116, log: "Microsoft-Windows-Windows Defender/Operational", cat: "defender", crit: "high",
      title: "Defender detected malware",
      desc: "Microsoft Defender detected malware or unwanted software, naming the threat, the file/process, and the user.",
      sec: "A direct detection. Read alongside 1117 to confirm the remediation actually succeeded." },
    { id: 1117, log: "Microsoft-Windows-Windows Defender/Operational", cat: "defender", crit: "medium",
      title: "Defender took action against malware",
      desc: "Defender performed a remediation action (quarantine, remove, block) on a detected threat." },
    { id: 5001, log: "Microsoft-Windows-Windows Defender/Operational", cat: "defender", crit: "high",
      title: "Defender real-time protection was disabled",
      desc: "Real-time protection was turned off.",
      sec: "Disabling AV is a common precursor to payload execution. Alert unless it's an expected maintenance action." },
    { id: 5007, log: "Microsoft-Windows-Windows Defender/Operational", cat: "defender", crit: "medium",
      title: "Defender configuration changed",
      desc: "A Defender setting was modified (e.g. an exclusion added).",
      sec: "Attackers add path/process exclusions to blind Defender before running tools. Scrutinize new exclusions." },
    { id: 1006, log: "Microsoft-Windows-Windows Defender/Operational", cat: "defender", crit: "high",
      title: "Defender antimalware engine found malware (scan)",
      desc: "The scan engine found malware during a scan." },

    // ---- RDP / Terminal Services (operational) ----
    { id: 1149, log: "Microsoft-Windows-TerminalServices-RemoteConnectionManager/Operational", cat: "rdp", crit: "medium",
      title: "RDP: user authentication succeeded (network-level)",
      desc: "An RDP connection passed network-level authentication, with the user and source IP. Note: this fires before full logon and even for some failed sessions.",
      sec: "Primary source-IP record for RDP access. Correlate with 4624 type 10 to confirm interactive logon." },
    { id: 21, log: "Microsoft-Windows-TerminalServices-LocalSessionManager/Operational", cat: "rdp", crit: "low",
      title: "RDP: session logon succeeded",
      desc: "A Terminal Services session logon completed, with the user and source address." },
    { id: 24, log: "Microsoft-Windows-TerminalServices-LocalSessionManager/Operational", cat: "rdp", crit: "low",
      title: "RDP: session was disconnected",
      desc: "An RDP session disconnected but keeps running." },
    { id: 25, log: "Microsoft-Windows-TerminalServices-LocalSessionManager/Operational", cat: "rdp", crit: "low",
      title: "RDP: session reconnection succeeded",
      desc: "A disconnected RDP session was reconnected, with the source address." },

    // ---- AppLocker (operational) ----
    { id: 8003, log: "Microsoft-Windows-AppLocker/EXE and DLL", cat: "applocker", crit: "low",
      title: "AppLocker: file allowed but would be blocked (audit mode)",
      desc: "In audit-only mode, a file ran that a rule would have blocked in enforce mode.",
      sec: "Audit-mode 8003s are your roadmap before turning on enforcement — and can catch tooling in the meantime." },
    { id: 8004, log: "Microsoft-Windows-AppLocker/EXE and DLL", cat: "applocker", crit: "medium",
      title: "AppLocker: file was blocked (enforce mode)",
      desc: "AppLocker prevented an executable/DLL from running.",
      sec: "A blocked binary can be a blocked attack — or a false positive. Investigate the path and publisher." },
    { id: 8006, log: "Microsoft-Windows-AppLocker/MSI and Script", cat: "applocker", crit: "low",
      title: "AppLocker: script/installer allowed (audit mode)",
      desc: "A script or MSI ran that would have been blocked in enforce mode." },
    { id: 8007, log: "Microsoft-Windows-AppLocker/MSI and Script", cat: "applocker", crit: "medium",
      title: "AppLocker: script/installer was blocked",
      desc: "AppLocker blocked a script (ps1/vbs/js/cmd) or MSI from running." },

    // ---- Firewall (operational) ----
    { id: 2004, log: "Microsoft-Windows-Windows Firewall With Advanced Security/Firewall", cat: "firewall", crit: "low",
      title: "A firewall rule was added",
      desc: "A new Windows Firewall rule was created, with its name, ports, and program.",
      sec: "Attackers add inbound-allow rules to open a listener or enable remote access (e.g. RDP). Review new rules." },
    { id: 2005, log: "Microsoft-Windows-Windows Firewall With Advanced Security/Firewall", cat: "firewall", crit: "low",
      title: "A firewall rule was modified",
      desc: "An existing firewall rule changed." },
    { id: 2006, log: "Microsoft-Windows-Windows Firewall With Advanced Security/Firewall", cat: "firewall", crit: "low",
      title: "A firewall rule was deleted",
      desc: "A firewall rule was removed — potentially one that was blocking the attacker." },
    { id: 2003, log: "Microsoft-Windows-Windows Firewall With Advanced Security/Firewall", cat: "firewall", crit: "medium",
      title: "The firewall profile setting was changed",
      desc: "A firewall profile setting changed (e.g. the firewall being turned off for a profile).",
      sec: "Disabling the firewall for the domain/private profile clears the way for lateral tooling." },

    // ---- WMI (operational) ----
    { id: 5861, log: "Microsoft-Windows-WMI-Activity/Operational", cat: "wmi", crit: "high",
      title: "WMI: permanent event consumer registered",
      desc: "A permanent WMI event subscription (filter + consumer binding) was registered — one of the stealthiest persistence mechanisms.",
      sec: "WMI event-consumer persistence survives reboots and hides from most autorun tools. A registered CommandLineEventConsumer or ActiveScriptEventConsumer is a strong IOC." }
  ];

  // Every entry gets a ready-to-run Get-WinEvent query keyed on its own
  // channel and id, unless it defined a custom one.
  E.forEach(function (e) { if (!e.query) e.query = q(e.log, e.id); });

  return E;
})();
